# Generated by Django 3.2.7 on 2022-01-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default_profile.png', upload_to='profile_photos', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='receive_updates',
            field=models.BooleanField(default=False, help_text='با فعال کردن این گزینه هرگاه مقاله جدیدی در سایت منتشر شود ایمیل اطلاع رسانی برای شما ارسال خواهد شد.', verbose_name='دریافت آپدیت ها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'این ایمیل قبلا ثبت شده است.'}, max_length=254, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
    ]
