# Generated by Django 3.2.7 on 2021-11-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replied_to',
            new_name='parent',
        ),
    ]
