# Generated by Django 3.2.7 on 2021-12-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='metatags',
            field=models.TextField(blank=True, default=None, max_length=450),
        ),
    ]
