# Generated by Django 3.2.7 on 2021-12-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contactmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1500, verbose_name='دیدگاه شما'),
        ),
    ]
